# -*- coding: utf-8 -*-
"""код_для_url.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M5Aqa0hwF4CnYUD-m5jNU2ptsNKflNSi
"""

import requests
from bs4 import BeautifulSoup
import re

def find_neologism(word, url):
    # Виконуємо запит на веб-сторінку
    response = requests.get(url)

    # Перевіряємо, чи вдалося отримати доступ до сторінки
    if response.status_code == 200:
        # Розбираємо HTML-код сторінки за допомогою BeautifulSoup
        soup = BeautifulSoup(response.content, 'html.parser')

        # Знаходимо всі посилання на сторінки з неологізмами
        links = soup.find_all('a', href=re.compile(r'cgi-bin/u/book/sis\.pl\?Article=\d+&action=show'))

        # Перевіряємо кожне посилання
        for link in links:
            # Перевіряємо, чи містить слово користувача в посиланні
            if word.lower() in link.text.lower().strip():
                return True

        # Якщо жодного неологізму не знайдено
        return False
    else:
        print("Не вдалося отримати доступ до сторінки.")
        return False

def main():
    # URL-адреса веб-сторінки з неологізмами
    url = "https://www.jnsm.com.ua/cgi-bin/u/book/mySIS.pl?showSISid=46609864-6427&action=showSIS&h=f"

    # Користувач вводить слово для перевірки
    word = input("Введіть слово для перевірки: ").strip()

    # Перевіряємо, чи є слово неологізмом
    if find_neologism(word, url):
        print("Так, це слово є неологізмом.")
    else:
        print("Ні, це слово не є неологізмом.")

if __name__ == "__main__":
    main()